import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { IMCResult } from '../types';
import { calculateDailyCalories, calculateIdealWeight } from '../utils/imcCalculator';

interface Props { result: IMCResult; height: number; weight: number; age: number; gender: 'male' | 'female' }

const ResultCard: React.FC<Props> = ({ result, height, weight, age, gender }) => {
  const ideal = calculateIdealWeight(height); const calories = calculateDailyCalories(weight, height, age, gender);
  const progress = Math.max(0, Math.min(100, ((result.value - 15) / 25) * 100));
  return <View style={styles.container}><View style={styles.resultHeader}><Text style={styles.title}>Resultado</Text></View>
    <View style={styles.hero}><Text style={[styles.imc, { color: result.color }]}>{result.value.toFixed(1)}</Text><Text style={[styles.category, { color: result.color }]}>{result.category}</Text><Text style={styles.description}>{result.description}</Text></View>
    <View style={styles.classification}><View style={styles.labels}><Text style={[styles.scaleLabel, { flex: 3.5 }]}>Baixo peso</Text><Text style={[styles.scaleLabel, { flex: 6.5 }]}>Normal</Text><Text style={[styles.scaleLabel, { flex: 5 }]}>Sobrepeso</Text><Text style={[styles.scaleLabel, { flex: 10 }]}>Obesidade</Text></View><View style={styles.bar}><View style={[styles.segment, { flex: 3.5, backgroundColor: '#38BDF8' }]} /><View style={[styles.segment, { flex: 6.5, backgroundColor: '#10B981' }]} /><View style={[styles.segment, { flex: 5, backgroundColor: '#FBBF24' }]} /><View style={[styles.segment, { flex: 10, backgroundColor: '#F97316' }]} /><View style={[styles.marker, { left: `${progress}%`, backgroundColor: result.color }]} /></View><View style={styles.ticks}><Text>15</Text><Text>18.5</Text><Text>25</Text><Text>30</Text><Text>40</Text></View></View>
    <View style={styles.grid}>{[["weight-kilogram", 'Peso ideal', `${ideal.min} – ${ideal.max} kg`, '#2563EB'], ['fire', 'Calorias/dia', `${calories} kcal`, '#F97316'], ['ruler', 'Altura', `${height} cm`, '#0F766E'], ['scale-bathroom', 'Peso atual', `${weight} kg`, '#7C3AED']].map(([icon, label, value, color]) => <View key={label} style={styles.info}><Icon name={icon as string} size={18} color={color as string} /><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value}</Text></View>)}</View>
    <View style={styles.recommendations}><Text style={styles.recommendationsTitle}>Recomendações</Text>{result.recommendations.slice(0, 3).map((recommendation) => <View key={recommendation} style={styles.recommendation}><Icon name="check" size={17} color="#2563EB" /><Text style={styles.recommendationText}>{recommendation}</Text></View>)}</View>
  </View>;
};

const styles = StyleSheet.create({ container: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 4, padding: 16, marginTop: 20 }, resultHeader: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' }, title: { fontSize: 20, fontWeight: '700', color: '#0F172A', textAlign: 'center' }, hero: { alignItems: 'center', paddingVertical: 18 }, imc: { fontSize: 54, lineHeight: 62, fontWeight: '800', marginTop: 2 }, category: { fontSize: 18, fontWeight: '700' }, description: { fontSize: 13, color: '#64748B', marginTop: 5 }, classification: { marginBottom: 22 }, labels: { flexDirection: 'row', marginBottom: 8 }, scaleLabel: { flex: 1, fontSize: 10, color: '#64748B', textAlign: 'center' }, bar: { height: 9, flexDirection: 'row', overflow: 'hidden', borderRadius: 4, position: 'relative' }, segment: { height: '100%' }, marker: { position: 'absolute', top: -5, marginLeft: -2, width: 4, height: 19, borderRadius: 2 }, ticks: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 5, color: '#94A3B8' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 18 }, info: { width: '48%', minHeight: 78, borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 4, padding: 10 }, infoLabel: { fontSize: 12, color: '#64748B', marginTop: 5 }, infoValue: { fontSize: 15, fontWeight: '700', color: '#0F172A', marginTop: 2 }, recommendations: { backgroundColor: '#EFF6FF', borderLeftWidth: 3, borderLeftColor: '#2563EB', padding: 12 }, recommendationsTitle: { fontSize: 15, fontWeight: '700', color: '#1E3A8A', marginBottom: 8 }, recommendation: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 5 }, recommendationText: { flex: 1, marginLeft: 7, color: '#1E40AF', fontSize: 13, lineHeight: 18 } });

export default ResultCard;
